services:
  - type: web
    name: real-estate-django
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn real_estate_project.wsgi:application"
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: real-estate-db
          property: connectionString

databases:
  - name: real-estate-db
    plan: free
