services:
  - type: web
    name: real-estate-django
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn real_estate_project.wsgi:application"
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true

databases:
  - name: real-estate-db
    plan: free
